
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package Analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int ATTR_NOMBRE = 17;
  public static final int CADENA = 3;
  public static final int IGUAL = 11;
  public static final int TAG_AP_C = 16;
  public static final int TAG_AP_A = 15;
  public static final int FLECHA = 21;
  public static final int LLAV_IZQ = 7;
  public static final int ID = 2;
  public static final int LLAV_DER = 8;
  public static final int DOS_PUNTOS = 23;
  public static final int COMA = 10;
  public static final int MAYOR = 12;
  public static final int EOF = 0;
  public static final int PR_TRANSI = 4;
  public static final int PT_COMA = 9;
  public static final int SIMBOLO = 19;
  public static final int PAR_IZQ = 24;
  public static final int VERTICAL = 22;
  public static final int PR_VER = 5;
  public static final int error = 1;
  public static final int PAR_DER = 25;
  public static final int TAG_AFD_C = 14;
  public static final int ESTADO = 18;
  public static final int VACIO = 20;
  public static final int TAG_AFD_A = 13;
  public static final int PR_DESC = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "CADENA",
  "PR_TRANSI",
  "PR_VER",
  "PR_DESC",
  "LLAV_IZQ",
  "LLAV_DER",
  "PT_COMA",
  "COMA",
  "IGUAL",
  "MAYOR",
  "TAG_AFD_A",
  "TAG_AFD_C",
  "TAG_AP_A",
  "TAG_AP_C",
  "ATTR_NOMBRE",
  "ESTADO",
  "SIMBOLO",
  "VACIO",
  "FLECHA",
  "VERTICAL",
  "DOS_PUNTOS",
  "PAR_IZQ",
  "PAR_DER"
  };
}

